# Copyright (c) 2015, the Dart GL extension authors. All rights reserved.
# Please see the AUTHORS file for details. Use of this source code is governed
# by a BSD-style license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd
"""Custom templates for the GL extension.

Includes license header, C header ifdef guards, and C includes, etc.
"""

GL_LICENSE_HEADER = (
    """// Copyright (c) 2015, the Dart GL extension authors. All rights reserved.
// Please see the AUTHORS file for details. Use of this source code is governed
// by a BSD-style license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

// This file is auto-generated by scripts in the tools/ directory.
"""
)

GL_GENERATED_BINDINGS_HEADER_HEADER = GL_LICENSE_HEADER + (
    """#ifndef THIRD_PARTY_DART_GL_LIB_SRC_GENERATED_GENERATED_BINDINGS_H_
#define THIRD_PARTY_DART_GL_LIB_SRC_GENERATED_GENERATED_BINDINGS_H_

#include "third_party/dart_lang/runtime/include/dart_api.h"

""")

GL_GENERATED_BINDINGS_HEADER_FOOTER = (
    """

#endif // THIRD_PARTY_DART_GL_LIB_SRC_GENERATED_GENERATED_BINDINGS_H_"""
)

GL_GENERATED_BINDINGS_HEADER = GL_LICENSE_HEADER + (
    """#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "third_party/GL/gl/include/GLES2/gl2.h"
#include "third_party/dart_lang/runtime/include/dart_api.h"

#include "third_party/dart/gl/lib/src/util.h"
#include "third_party/dart/gl/lib/src/generated/gl_bindings.h"

""")

GL_DART_GENERATED_FUNCTIONS_HEADER = GL_LICENSE_HEADER + (
    """

part of gles2;

""")

GL_DART_GENERATED_CONSTANTS_HEADER = GL_LICENSE_HEADER + (
    """

part of gles2;

""")

GL_FUNCTION_LIST_HEADER_BODY = GL_LICENSE_HEADER + (
    """
#ifndef THIRD_PARTY_DART_GL_LIB_SRC_GENERATED_FUNCTION_LIST_H_
#define THIRD_PARTY_DART_GL_LIB_SRC_GENERATED_FUNCTION_LIST_H_

#include "third_party/dart_lang/runtime/include/dart_api.h"

struct FunctionLookup {
  const char* name;
  Dart_NativeFunction function;
};

extern const struct FunctionLookup *function_list;

#endif // THIRD_PARTY_DART_GL_LIB_SRC_GENERATED_FUNCTION_LIST_H_
""")

GL_FUNCTION_LIST_HEADER = GL_LICENSE_HEADER + (
    """
#include <stdlib.h>
#include "third_party/dart_lang/runtime/include/dart_api.h"

#include "third_party/dart/gl/lib/src/manual_bindings.h"
#include "third_party/dart/gl/lib/src/generated/function_list.h"
#include "third_party/dart/gl/lib/src/generated/gl_bindings.h"

// function_list is used by ResolveName in lib/src/gl_extension.cc.
const struct FunctionLookup _function_list[] = {
""")

GL_FUNCTION_LIST_FOOTER = ("""
    {NULL, NULL}};
// This prevents the compiler from complaining about initializing improperly.
const struct FunctionLookup *function_list = _function_list;
""")

GL_ARGUMENTS_ARRAY_TEMPLATE = (
    "arguments[{i}] = HandleError({new_handle_call});"
)
